<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="google-signin-client_id" content="612782885576-g5a24fjm5m84i8rmun5333so7pgj8dvp.apps.googleusercontent.com">
    <meta content="#5b32b4" name="theme-color"/>
    <meta content="#5b32b4" name="msapplication-navbutton-color"/>
    <meta content="#5b32b4" name="apple-mobile-web-app-status-bar-style"/>
    <meta content="#5b32b4" name="theme-color"/>

    <!-- Favicons -->
    <link rel="icon" href="assets/img/icon.png">

    <!-- Core Stylesheet -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/magnific-popup.css" rel="stylesheet">
    <link href="assets/css/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/css/slick.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="assets/css/themify-icons.css" rel="stylesheet">
    <link href="assets/css/ionicons.min.css" rel="stylesheet">
    <!-- Responsive CSS -->
    <link href="assets/css/responsive.css" rel="stylesheet">
    <script src="lib/fusioncharts/js/fusioncharts.js" type="text/javascript"></script>
    <script src="lib/fusioncharts/js/maps/fusioncharts.world.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>
        <?= $title ?>
    </title>
</head>

<body>
    <section>
        <!--  Todos os arquivos das views serão carregados aqui  -->
        <?php $this->controller->renderView(); ?>
    </section>
    <!--  Arquivos JS  -->
    <!-- Jquery-2.2.4 JS -->
    <script src="assets/js/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="assets/js/popper.min.js"></script>
    <!-- Bootstrap-4 Beta JS -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- All Plugins JS -->
    <script src="assets/js/plugins.js"></script>
    <!-- Slick Slider Js-->
    <script src="assets/js/slick.min.js"></script>
    <!-- Footer Reveal JS -->
    <script src="assets/js/footer-reveal.min.js"></script>
    <!-- Active JS -->
    <script src="assets/js/active.js"></script>
    
	<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=Aoq1PkOuQGT5XcbPg3uSKVtyLjdn5C3ErWV32mADFuqnrDCVfcr1L7oMYuHd9vU0&callback=loadMapScenario'
	 async defer></script>
</body>

</html>
