

<!-- Preloader Start -->
    <div id="preloader">
        <div class="colorlib-load"></div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header_area animated">
        <div class="container-fluid">
            <div class="row align-items-center">
                <!-- Menu Area Start -->
                <div class="col-12 col-lg-10">
                    <div class="menu_area">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <!-- Logo -->
                            <a class="navbar-brand" href="#">T.A.T.</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ca-navbar"
                                aria-controls="ca-navbar" aria-expanded="false" aria-label="Toggle navigation"><span
                                    class="navbar-toggler-icon"></span></button>
                            <!-- Menu Area -->
                        </nav>
                    </div>
                </div><br>
                <!-- Signup btn -->
                <div class="col-12 col-lg-2">
                    <div class="sing-up-button d-none d-lg-block">
                        <a href="home">Home</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Wellcome Area Start ***** -->
    <section class="wellcome_area clearfix" id="cadastro">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-md">
                    <div class="wellcome-heading">
                        <h2>Relatos</h2>
                        <h3>Blue</h3>
                        <p>Seus dados estão protegidos e são secretos!</p>
                    </div>
                    <div class="get-start-area">
                        <!-- Form Start -->
                        <form action="" method="get" class="form-inline">
                            <input type="text" class="form-control email" name="cidade" placeholder="Nome da cidade" required>
                            <input type="submit" class="submit" value="Pesquisar">
                        </form>
                        <!-- Form End -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Welcome thumb --
        <div class="welcome-thumb wow fadeInDown" data-wow-delay="0.5s">
            <img src="img/bg-img/welcome-img.png" alt="">
        </div>-->
    </section>
    <!-- ***** Wellcome Area End ***** -->

    <!-- ***** Special Area Start ***** -->
    <!-- ***** Client Feedback Area Start ***** -->
    <!-- ***** Client Feedback Area Start ***** -->
    <section class="clients-feedback-area bg-white section_padding_100 clearfix" id="testimonials">
        <div class="container">
            <div class="row justify-content-center">
                <?php
                    if( isset($_GET['cidade']) ){
                        $relatos = new BuscaRelatos();
                        
                        echo $relatos->buscar($_GET['cidade']);
                    }
                ?>
            </div>
        </div>
    </section>
    <!-- ***** Client Feedback Area End ***** -->
    <!-- ***** Special Area End ***** -->
    <br>
    <!-- ***** Footer Area Start ***** -->
    <footer class="footer-social-icon text-center section_padding_70 clearfix">
        <!-- footer logo -->
        <div class="footer-text">
            <h2>T.A.T.</h2>
        </div>
        <!-- social icon-->
        <div class="footer-social-icon">
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="#"><i class="active fa fa-twitter" aria-hidden="true"></i></a>
            <a href="#"> <i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
        </div>
    </footer>